[package]
name = "ecdh"
version = "0.1.0"
edition = "2021"

[dependencies]
rand_core = { version = "0.6.4", features = ["getrandom"] }
chacha20poly1305 = "0.10"
k256 = { version = "0.13.4", features = ["ecdh", "serde"] }


