[package]
name = "fhe-zama"
version = "0.1.0"
edition = "2021"

[dependencies]
tfhe = { version = "0.9.0", features = [ "boolean", "shortint", "integer", "aarch64-unix" ] }
num-traits = "0.2.19"
bincode = "1.3.3"
serde = "1.0.210"
serde_json = "1.0.1"