[package]
name = "fhe-zama"
version = "0.1.0"
edition = "2021"

[dependencies]
tfhe = { version = "0.8.4", features = [ "boolean", "shortint", "integer", "aarch64-unix" ] }
serde = "1.0.210"
serde_json = "1.0.1"